site_name: Accessibility and Inclusiveness
site_url: https://page-and-maxence.github.io/accessibility-and-inclusiveness/

site_author: Maxence Vahedi & Page Magnier--Slimani
repo_name: Page-and-Maxence/accessibility-and-inclusiveness
repo_url: https://github.com/Page-and-Maxence/accessibility-and-inclusiveness

copyright: Maxence Vahedi & Page Magnier--Slimani CC BY-SA 4.0

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference